spring:
  datasource:
    #    url: jdbc:sqlserver://star-think.ddns.net:19830;databaseName=today-story
    url: jdbc:sqlserver://localhost:19830;databaseName=today-story
    username: reactuser
    password: reactpwd12#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


logging:
  level:
    com.bookflex: debug

jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.bookflex.backend.dto

server:
  port: 1722