spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver


logging:
  level:
    com.bookflex: debug

jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.bookflex.backend.dto